
services:
  backend:
    build: backend/
    ports:
      - "3000:3000"  # Adjust the port if needed
    environment:
      - NODE_ENV=production  # Add any other environment variables you need
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=ct648
    volumes:
      - ./backend:/app

    networks:
      - appnetwork

    depends_on:
      - postgres  # Ensure backend waits for the database to be ready

  frontend:
    build: frontend/
    ports:
      - "3001:5173"  # Adjust frontend port as needed

  postgres:
    image: postgres:15  # Specify the desired version of PostgreSQL
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=ct648
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

    networks:
      - appnetwork

volumes:
  postgres_data:  # Named volume for PostgreSQL data persistence

networks:
  appnetwork:
    driver: bridge
